apiVersion: v1
kind: ConfigMap
metadata:
  name: camera-front-config
  namespace: kindling
data:
  settings.js: |
    const setting = {
        apmServerConfig: {
            host: 'localhost',
            port: '2234',
        },
        profileConfig: {
            host: 'localhost',
            port: '9503',
        },
        traceFilePath: '/tmp/kindling',
        port: 9504,
    };
    module.exports = setting;