apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
  name: kindling-agent
  resourceVersion: "15122093"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kindling-agent
  uid: 8761e9af-aab2-49d2-be7e-ca4aae974508
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kindling-agent
subjects:
- kind: ServiceAccount
  name: kindling-agent
  namespace: kindling
