refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "log/kindling-agent.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - file

## 可针对单个模块开不同的日志模式
loggers:
  camera_agent::cpu_analyzer:
    level: info